apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: vote
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
#      - image: dockersamples/examplevotingapp_worker
      - image: pablolibo/examplevotingapp_worker
        name: worker
